language: csharp
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.4
    
install:
  - cd build
  - ./install-dotnet-script.sh  
script:  
  - dotnet dotnet-script/publish/dotnet-script.dll Build.csx